/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const NewGameGameIdLazyImport = createFileRoute('/new-game/$gameId')()
const JustoneGameIdLazyImport = createFileRoute('/justone/$gameId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NewGameGameIdLazyRoute = NewGameGameIdLazyImport.update({
  path: '/new-game/$gameId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/new-game.$gameId.lazy').then((d) => d.Route),
)

const JustoneGameIdLazyRoute = JustoneGameIdLazyImport.update({
  path: '/justone/$gameId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/justone.$gameId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/justone/$gameId': {
      preLoaderRoute: typeof JustoneGameIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/new-game/$gameId': {
      preLoaderRoute: typeof NewGameGameIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  JustoneGameIdLazyRoute,
  NewGameGameIdLazyRoute,
])

/* prettier-ignore-end */
